sudo: required

services:
  - docker

language: node_js
dist: trusty
node_js:
    - '8'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - npm run build

after_script:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker build -t "$REGISTRY_URL"/"$REGISTRY_IMAGE" .;
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$REGISTRY_URL";
      docker push "$REGISTRY_URL"/"$REGISTRY_IMAGE";
      fi

branches:
  only:
    - master